# SPDX-FileCopyrightText: Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---

- name: "Check whether network configurations are given."
  ansible.builtin.assert:
    that:
      - "netplan_ethernets is defined and netplan_ethernets | length > 0"

- name: "Gather package facts"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Check whether package ifupdown is installed"
  ansible.builtin.debug:
    msg: |
      "Package 'ifupdown' is installed in version '{{ ansible_facts.packages['ifupdown'][0].version }}'.
      Please consider removing it after Netplan role has been executed successfully."
  when: "'ifupdown' in ansible_facts.packages"

- name: "Install netplan packages."
  become: true
  ansible.builtin.package:
    name: "{{ netplan_packages }}"
    state: "present"
    update_cache: true

- name: "Delete pre-existing network settings files."
  when: "netplan_remove_existing_configs"
  block:
    - name: "Get netplan config files."
      ansible.builtin.find:
        paths: "{{ netplan_configuration_dir }}"
        file_type: "file"
        excludes:
          - "{{ netplan_configuration_file }}"
      register: "netplan_config_files"

    - name: "Remove netplan config files."
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "absent"
      with_items: "{{ netplan_config_files['files'] }}"

- name: "Create a netplan config file from template."
  ansible.builtin.template:
    src: "{{ netplan_configuration_file_template }}"
    dest: "{{ netplan_configuration_file_path }}"
    owner: "root"
    group: "root"
    mode: "0600"
    backup: true
  notify:
    - "Generate netplan networking"
    - "Apply netplan networking"
    - "Gather network facts"
...
